name: salat
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-195.0.dev

# Add regular dependencies here.
dependencies:
  hijri: ^3.0.0
  intl: ^0.18.1
  tabular: ^0.6.3+1
  timezone: ^0.9.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
