name: salat
description: a dart package that calculates salat times
version: 1.0.1
repository: https://github.com/Muslims-code/salat

environment:
  sdk: '>=2.12.0 <4.0.0'


# Add regular dependencies here.
dependencies:
  hijri: ^3.0.0
  intl: ^0.18.1
  tabular: ^0.6.3+1
  timezone: ^0.9.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
